# Generated by Django 3.2.7 on 2021-09-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Native',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('image', models.ImageField(default='', upload_to='templates/native_images/')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tech_academy.cohort')),
            ],
        ),
    ]
