# Generated by Django 3.2.7 on 2021-09-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='native',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tech_academy.cohort'),
        ),
    ]
