# Generated by Django 3.2.7 on 2021-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_academy', '0002_alter_native_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='native',
            name='image',
            field=models.ImageField(default='', upload_to='native_images/'),
        ),
    ]
