# Generated by Django 3.2.7 on 2021-09-22 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tech_academy', '0004_alter_native_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='native',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 40, 36, 391436, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('native', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tech_academy.native')),
            ],
        ),
    ]
