# Generated by Django 3.2.7 on 2021-09-22 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tech_academy', '0005_auto_20210922_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='thought_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='native',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 55, 56, 348236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thought',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 55, 56, 349235, tzinfo=utc)),
        ),
    ]
